class_name ReagentRegistry extends Node

## Preload-based lookup from a stable identifier string (matching the .tres base file
## name, e.g. "Tincture_Speed_Uncommon") to its ReagentData, mirroring
## StatusEffectRegistry (DirAccess-based discovery is unsafe on Android export).

const REAGENTS: Dictionary[String, ReagentData] = {
	"Fractured_Idol_Epic": preload("res://Data/Reagents/Fractured_Idol/Fractured_Idol_Epic.tres"),
	"Fractured_Idol_Legendary": preload("res://Data/Reagents/Fractured_Idol/Fractured_Idol_Legendary.tres"),
	"Fractured_Idol_Rare": preload("res://Data/Reagents/Fractured_Idol/Fractured_Idol_Rare.tres"),
	"Fractured_Idol_Uncommon": preload("res://Data/Reagents/Fractured_Idol/Fractured_Idol_Uncommon.tres"),
	"Purging_Tonic_Epic": preload("res://Data/Reagents/Purging_Tonic/Purging_Tonic_Epic.tres"),
	"Purging_Tonic_Legendary": preload("res://Data/Reagents/Purging_Tonic/Purging_Tonic_Legendary.tres"),
	"Purging_Tonic_Rare": preload("res://Data/Reagents/Purging_Tonic/Purging_Tonic_Rare.tres"),
	"Purging_Tonic_Uncommon": preload("res://Data/Reagents/Purging_Tonic/Purging_Tonic_Uncommon.tres"),
	"Restorative_Draught_Epic": preload("res://Data/Reagents/Restorative_Draught/Restorative_Draught_Epic.tres"),
	"Restorative_Draught_Legendary": preload("res://Data/Reagents/Restorative_Draught/Restorative_Draught_Legendary.tres"),
	"Restorative_Draught_Rare": preload("res://Data/Reagents/Restorative_Draught/Restorative_Draught_Rare.tres"),
	"Restorative_Draught_Uncommon": preload("res://Data/Reagents/Restorative_Draught/Restorative_Draught_Uncommon.tres"),
	"Rewinding_Grit_Epic": preload("res://Data/Reagents/Rewinding_Grit/Rewinding_Grit_Epic.tres"),
	"Rewinding_Grit_Legendary": preload("res://Data/Reagents/Rewinding_Grit/Rewinding_Grit_Legendary.tres"),
	"Rewinding_Grit_Rare": preload("res://Data/Reagents/Rewinding_Grit/Rewinding_Grit_Rare.tres"),
	"Rewinding_Grit_Uncommon": preload("res://Data/Reagents/Rewinding_Grit/Rewinding_Grit_Uncommon.tres"),
	"Second_Wind_Phial_Epic": preload("res://Data/Reagents/Second_Wind_Phial/Second_Wind_Phial_Epic.tres"),
	"Second_Wind_Phial_Legendary": preload("res://Data/Reagents/Second_Wind_Phial/Second_Wind_Phial_Legendary.tres"),
	"Second_Wind_Phial_Rare": preload("res://Data/Reagents/Second_Wind_Phial/Second_Wind_Phial_Rare.tres"),
	"Second_Wind_Phial_Uncommon": preload("res://Data/Reagents/Second_Wind_Phial/Second_Wind_Phial_Uncommon.tres"),
	"Thiefs_Regret_Epic": preload("res://Data/Reagents/Thiefs_Regret/Thiefs_Regret_Epic.tres"),
	"Thiefs_Regret_Legendary": preload("res://Data/Reagents/Thiefs_Regret/Thiefs_Regret_Legendary.tres"),
	"Thiefs_Regret_Rare": preload("res://Data/Reagents/Thiefs_Regret/Thiefs_Regret_Rare.tres"),
	"Thiefs_Regret_Uncommon": preload("res://Data/Reagents/Thiefs_Regret/Thiefs_Regret_Uncommon.tres"),
	"Tincture_Accuracy_Epic": preload("res://Data/Reagents/Tincture_Accuracy/Tincture_Accuracy_Epic.tres"),
	"Tincture_Accuracy_Legendary": preload("res://Data/Reagents/Tincture_Accuracy/Tincture_Accuracy_Legendary.tres"),
	"Tincture_Accuracy_Rare": preload("res://Data/Reagents/Tincture_Accuracy/Tincture_Accuracy_Rare.tres"),
	"Tincture_Accuracy_Uncommon": preload("res://Data/Reagents/Tincture_Accuracy/Tincture_Accuracy_Uncommon.tres"),
	"Tincture_Attack_Epic": preload("res://Data/Reagents/Tincture_Attack/Tincture_Attack_Epic.tres"),
	"Tincture_Attack_Legendary": preload("res://Data/Reagents/Tincture_Attack/Tincture_Attack_Legendary.tres"),
	"Tincture_Attack_Rare": preload("res://Data/Reagents/Tincture_Attack/Tincture_Attack_Rare.tres"),
	"Tincture_Attack_Uncommon": preload("res://Data/Reagents/Tincture_Attack/Tincture_Attack_Uncommon.tres"),
	"Tincture_CritChance_Epic": preload("res://Data/Reagents/Tincture_CritChance/Tincture_CritChance_Epic.tres"),
	"Tincture_CritChance_Legendary": preload("res://Data/Reagents/Tincture_CritChance/Tincture_CritChance_Legendary.tres"),
	"Tincture_CritChance_Rare": preload("res://Data/Reagents/Tincture_CritChance/Tincture_CritChance_Rare.tres"),
	"Tincture_CritChance_Uncommon": preload("res://Data/Reagents/Tincture_CritChance/Tincture_CritChance_Uncommon.tres"),
	"Tincture_CritDamage_Epic": preload("res://Data/Reagents/Tincture_CritDamage/Tincture_CritDamage_Epic.tres"),
	"Tincture_CritDamage_Legendary": preload("res://Data/Reagents/Tincture_CritDamage/Tincture_CritDamage_Legendary.tres"),
	"Tincture_CritDamage_Rare": preload("res://Data/Reagents/Tincture_CritDamage/Tincture_CritDamage_Rare.tres"),
	"Tincture_CritDamage_Uncommon": preload("res://Data/Reagents/Tincture_CritDamage/Tincture_CritDamage_Uncommon.tres"),
	"Tincture_Defence_Epic": preload("res://Data/Reagents/Tincture_Defence/Tincture_Defence_Epic.tres"),
	"Tincture_Defence_Legendary": preload("res://Data/Reagents/Tincture_Defence/Tincture_Defence_Legendary.tres"),
	"Tincture_Defence_Rare": preload("res://Data/Reagents/Tincture_Defence/Tincture_Defence_Rare.tres"),
	"Tincture_Defence_Uncommon": preload("res://Data/Reagents/Tincture_Defence/Tincture_Defence_Uncommon.tres"),
	"Tincture_Knowledge_Epic": preload("res://Data/Reagents/Tincture_Knowledge/Tincture_Knowledge_Epic.tres"),
	"Tincture_Knowledge_Legendary": preload("res://Data/Reagents/Tincture_Knowledge/Tincture_Knowledge_Legendary.tres"),
	"Tincture_Knowledge_Rare": preload("res://Data/Reagents/Tincture_Knowledge/Tincture_Knowledge_Rare.tres"),
	"Tincture_Knowledge_Uncommon": preload("res://Data/Reagents/Tincture_Knowledge/Tincture_Knowledge_Uncommon.tres"),
	"Tincture_Mysticism_Epic": preload("res://Data/Reagents/Tincture_Mysticism/Tincture_Mysticism_Epic.tres"),
	"Tincture_Mysticism_Legendary": preload("res://Data/Reagents/Tincture_Mysticism/Tincture_Mysticism_Legendary.tres"),
	"Tincture_Mysticism_Rare": preload("res://Data/Reagents/Tincture_Mysticism/Tincture_Mysticism_Rare.tres"),
	"Tincture_Mysticism_Uncommon": preload("res://Data/Reagents/Tincture_Mysticism/Tincture_Mysticism_Uncommon.tres"),
	"Tincture_Resistance_Epic": preload("res://Data/Reagents/Tincture_Resistance/Tincture_Resistance_Epic.tres"),
	"Tincture_Resistance_Legendary": preload("res://Data/Reagents/Tincture_Resistance/Tincture_Resistance_Legendary.tres"),
	"Tincture_Resistance_Rare": preload("res://Data/Reagents/Tincture_Resistance/Tincture_Resistance_Rare.tres"),
	"Tincture_Resistance_Uncommon": preload("res://Data/Reagents/Tincture_Resistance/Tincture_Resistance_Uncommon.tres"),
	"Tincture_Speed_Epic": preload("res://Data/Reagents/Tincture_Speed/Tincture_Speed_Epic.tres"),
	"Tincture_Speed_Legendary": preload("res://Data/Reagents/Tincture_Speed/Tincture_Speed_Legendary.tres"),
	"Tincture_Speed_Rare": preload("res://Data/Reagents/Tincture_Speed/Tincture_Speed_Rare.tres"),
	"Tincture_Speed_Uncommon": preload("res://Data/Reagents/Tincture_Speed/Tincture_Speed_Uncommon.tres"),
	"Unrefined_Residue_Epic": preload("res://Data/Reagents/Unrefined_Residue/Unrefined_Residue_Epic.tres"),
	"Unrefined_Residue_Legendary": preload("res://Data/Reagents/Unrefined_Residue/Unrefined_Residue_Legendary.tres"),
	"Unrefined_Residue_Rare": preload("res://Data/Reagents/Unrefined_Residue/Unrefined_Residue_Rare.tres"),
	"Unrefined_Residue_Uncommon": preload("res://Data/Reagents/Unrefined_Residue/Unrefined_Residue_Uncommon.tres"),
	"Zone_Dissolving_Salts_Epic": preload("res://Data/Reagents/Zone_Dissolving_Salts/Zone_Dissolving_Salts_Epic.tres"),
	"Zone_Dissolving_Salts_Legendary": preload(
			"res://Data/Reagents/Zone_Dissolving_Salts/Zone_Dissolving_Salts_Legendary.tres"),
	"Zone_Dissolving_Salts_Rare": preload("res://Data/Reagents/Zone_Dissolving_Salts/Zone_Dissolving_Salts_Rare.tres"),
	"Zone_Dissolving_Salts_Uncommon": preload(
			"res://Data/Reagents/Zone_Dissolving_Salts/Zone_Dissolving_Salts_Uncommon.tres"),
}

static func Get(p_id: String) -> ReagentData:
	return REAGENTS.get(p_id)
