class_name RelicEffect extends CharacterTrait

## Every Relic_Design.md entry ladders across all five Rarity steps (Common through
## Legendary) rather than starting at Uncommon the way a character trait's ladder
## usually does, since a Relic can drop as Common. Index 0 is Common, index 4 Legendary.
var _magnitude_by_rarity: Array[float] = [0.0, 0.0, 0.0, 0.0, 0.0]

func Magnitude() -> float:
	var index: int = int(_owner_rarity) - 1
	if(index < 0 or index >= _magnitude_by_rarity.size()):
		return 0.0
	return _magnitude_by_rarity[index]

## Placeholder Relic icons are generated by hand (Scripts/Debug/generate_placeholder_icons.gd)
## rather than at code-review time, so a subclass's Init() can run before its icon file
## exists on disk. Loads it if present and leaves _trait_texture null otherwise, rather than
## erroring the way a raw load() call does on a missing path.
static func LoadIcon(p_path: String) -> Texture2D:
	if(ResourceLoader.exists(p_path)):
		return load(p_path)
	return null
